name: Emojify PR Title

on: pull_request

jobs:
  emojify-pr-title:
    runs-on: ubuntu-latest
    name: Emojify PR Title
    use-emoji-map: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emojify PR Title
        uses: pineapplelol/emojify-pr-title@v1.2
